name: ekg_vision_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  mongo_dart: ^0.10.0
  shelf: ^1.4.0
  crypto: ^3.0.2
  dart_jsonwebtoken: ^3.2.0
  shelf_multipart: ^2.0.1
  mime: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
